trialData <- read.csv2("household_power_consumption.txt")
trialData$date_normed <- as.Date(trialData$Date, format="%d/%m/%Y")
trialSub <- subset(trialData, date_normed >= "2007-02-01" & date_normed <= "2007-02-02")
trialSub$datetimenorm <- strptime(paste(trialSub$Date, trialSub$Time, sep=" "), format = "%d/%m/%Y %H:%M:%S"))
png(file = "plot3.png")
with(trialSub, plot(datetimenorm, as.numeric(as.character(Sub_metering_1)), type = "l", xlab = "", ylab="Energy Sub Metering", col = "black"))
lines(trialSub$datetimenorm, as.numeric(as.character(trialSub$Sub_metering_2)), col = "red")
lines(trialSub$datetimenorm, as.numeric(as.character(trialSub$Sub_metering_3)), col = "blue")
legend("topright",  lwd = 2, col = c("black",  "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()